# Exported from:        http://Anas-MacBook-Pro-2.local:5516/
# Release version:      24.1.0
# Date created:         Tue Jun 03 11:31:36 CEST 2025

---
apiVersion: xl-release/v1
kind: Applications
metadata:
  path: /
  home: Samples & Tutorials
spec:
- name: app1
  type: xlrelease.Application
  correlationUid: b7acd8fd-044f-4926-a119-ce7d3ceeb0fb
  applicationSource:
    type: deploy.ApplicationSource
    serverUrl: http://host.k3d.internal:4516
    applicationPath: "[app1](http://host.k3d.internal:4516/#/explorer?ciId=Applications/app1)"
  environments:
  - env1
