# Exported from:        http://Anas-MacBook-Pro-2.local:5516/
# Release version:      24.1.0
# Date created:         Mon Jun 09 10:41:20 CEST 2025

---
apiVersion: xl-release/v1
kind: Applications
metadata:
  path: /
  home: Samples & Tutorials
spec:
- name: app1
  type: xlrelease.Application
  correlationUid: b7acd8fd-044f-4926-a119-ce7d3ceeb0fb
  applicationSource:
    type: deploy.ApplicationSource
    serverUrl: http://host.k3d.internal:4516
    applicationPath: "[app1](http://host.k3d.internal:4516/#/explorer?ciId=Applications/app1)"
  environments:
  - env1
- name: appF
  type: xlrelease.Application
  correlationUid: 0f7290f2-10ca-4586-a13d-4a4d9139cf6b
  applicationSource:
    type: deploy.ApplicationSource
    serverUrl: http://host.k3d.internal:4516
    applicationPath: "[appF](http://host.k3d.internal:4516/#/explorer?ciId=Applications/test1/appF)"
  environments:
  - env1
