# Exported from:        http://Anas-MacBook-Pro-2.local:5516/
# Release version:      24.1.0
# Date created:         Mon Jun 09 12:53:06 CEST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Samples & Tutorials
spec:
- name: endpoint
  type: events.PostWebhookEndpoint
  path: deploy
  authentication:
    type: events.NoAuthentication
- name: deploy config
  type: deploy.DeploymentConfig
- name: deploy
  type: digitalai.DeployServer
  url: http://host.k3d.internal:4516
  username: admin
  password: !value "digitalai_DeployServer_deploy_password"
- name: k8s
  type: kubernetes.APIServer
  url: https://host.k3d.internal:50122
  k8sAuthenticationMethod: Client Certificate
  clientCrt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJUjlaWmJoRkd1R3N3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelEzTWpnM016WTBNQjRYRFRJMU1EVXhOVEExTXpZd05Gb1hEVEkyTURVeApOVEExTXpZd05Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJEUkdVN3MzUkZvK2dGWmsKWnpBVHphSDBqbzZ0UGhTQ3MzVXo3ZkpUWEZmcUR4SzhXQzQ5Nk1VSFoyaTJTd2FnN0JXWWhTSWNhZGpiOHRpWAoveGhiakxpalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUy9OamlYeUpnQUNFVnhUUTFLZENsUGhUczE3ekFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlCR0QwYmwwUC9oemxreW55bkpJK0VLN3VvWmFidGNFOE5oL2psWTQxMWdUQUloQUlhaWs4akVCMjlSdy9mNwpKbGRFa1k0OG1FVk4wVUZYbDFwNmQwaHVoZjlaCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTkRjeU9EY3pOalF3SGhjTk1qVXdOVEUxTURVek5qQTBXaGNOTXpVd05URXpNRFV6TmpBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTkRjeU9EY3pOalF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRTWlUWjN6VjFkMGc2L01MU1FZenZUVnJ1dWE1SlRTK3l2bDkveGFhUmoKanNEOVVieG4ybElvM2pYOEQ5MzJKRlpuSHc5cEFCcStsbHhhQ2I1dXZacnNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXZ6WTRsOGlZQUFoRmNVME5TblFwClQ0VTdOZTh3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVBMOTJsVmFUcWdsbUlGb05vZGUzbysxNjZ2bkJwcmQKWVVFeFRFQkkyUTRLQWlCYWpIbitlZkhRenNGd0RZOGJBclA5bzQvSzBndWkrSnVCczVudzFvcVl4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  clientKey: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUx2MG5xc1liS0FUSngyK1F4elVKOWR2aVo3bVNMSWZYeEQxeWk4Q0pxQU1vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTkVaVHV6ZEVXajZBVm1Sbk1CUE5vZlNPanEwK0ZJS3pkVFB0OGxOY1Yrb1BFcnhZTGozbwp4UWRuYUxaTEJxRHNGWmlGSWh4cDJOdnkySmYvR0Z1TXVBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  insecure: true
  CA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTkRjeU9EY3pOalF3SGhjTk1qVXdOVEUxTURVek5qQTBXaGNOTXpVd05URXpNRFV6TmpBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTkRjeU9EY3pOalF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRN1ZKdmwzeHIyT0J1RXJIT0psMmNDa3JDVVlORnhGVE1mbEhhL0JDZUoKeWdxRjBZSms4RzBuSThHa1JHd2hXV2tUeWpnTjNLckZSQ1drNHB2bkVmaC9vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU10eTFDcUhlV3E2N0Y2WDd4aVQ1ClFpemI0VUV3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnRWRMb21DamcxZzVMVUZzUzYvU1RYdi9Kb2kwRldaRy8KZm52MG1CcEZDVlFDSVFENzlRSEErMjcwbjF1WjhTTTNmeDNMSGxNayt3aDdLdklHTW5xOTNXdHkrUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
- name: deploy webhook
  type: deploy.StatusWebhookEventSource
  eventSource: endpoint
  sourceServer: deploy
  liveDeploymentConfigs:
  - deploy config
