# Exported from:        http://Mac:5516/
# Release version:      24.1.0
# Date created:         Fri Jun 06 12:22:35 CEST 2025

---
apiVersion: xl-release/v1
kind: Environments
metadata:
  path: /
  home: Samples & Tutorials
spec:
- name: env1
  type: xlrelease.Environment
  correlationUid: 0fd4c51f-b700-43d3-9a85-4aacefc4a52e
  description: "Target: http://host.k3d.internal:4516/#/explorer?ciId=Environments/env1"
  stage: Unknown
  deploymentTarget:
    type: deploy.DeploymentTarget
    targetUrl: http://host.k3d.internal:4516/#/explorer?ciId=Environments/env1
    environmentPath: "[env1](http://host.k3d.internal:4516/#/explorer?ciId=Environments/env1)"
