# Exported from:        http://Anas-MacBook-Pro-2.local:5516/
# Release version:      24.1.0
# Date created:         Thu Jun 05 11:04:13 CEST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Trigger_deploy test.yaml
