# Exported from:        http://Anas-MacBook-Pro-2.local:5516/
# Release version:      24.1.0
# Date created:         Mon Jun 09 20:16:19 CEST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Samples & Tutorials
spec:
- name: event
  type: events.EventBasedTrigger
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: event release
  - type: xlrelease.StringValue
    targetProperty: template
    value: Configure Release
  - type: xlrelease.StringValue
    targetProperty: releaseFolder
    value: ./
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: deploy webhook
  eventType: events.DeploymentServerEvent
